/// Renders the Python `dmg-settings.py` file that `dmgbuild` consumes.
///
/// The layout follows the W.Prep DMG guide's "don't create files you'd
/// need to hide" rule:
///   - background is a solid color (no `.background/` folder)
///   - no volume icon (no `.VolumeIcon.icns`)
///   - icon view, toolbars/sidebar off
///
/// Window centering math matches the guide: icons at x = W/2 - 120 and
/// x = W/2 + 120 so drag-and-drop feels balanced regardless of window size.
public struct DMGSettingsRenderer: Sendable {
    public init() {}

    public func render(_ dmg: DMGSection, appBundleName: String) -> String {
        let w = dmg.windowWidth
        let h = dmg.windowHeight
        let appX = w / 2 - 120
        let appsX = w / 2 + 120
        let y = h / 2 - 25

        return """
        # Generated by `relios dmg` — do not edit by hand.
        # Source of truth is [dmg] in relios.toml.
        import os

        application = os.environ['DMGBUILD_APP_PATH']
        appname = os.path.basename(application)

        format = 'UDZO'
        size = None
        files = [application]
        symlinks = {'Applications': '/Applications'}

        # No volume icon on purpose — avoids .VolumeIcon.icns in the DMG root.
        # (Don't add `icon = ...` back without re-reading the DMG guide.)

        # Solid background color — avoids a .background/ folder that Finder
        # started exposing on macOS 15+.
        background_color = '\(dmg.backgroundColor)'
        show_status_bar = False
        show_tab_view   = False
        show_toolbar    = False
        show_pathbar    = False
        show_sidebar    = False
        window_rect     = ((200, 120), (\(w), \(h)))
        default_view    = 'icon-view'
        arrange_by      = None

        icon_size = \(dmg.iconSize)
        text_size = 12
        icon_locations = {
            appname:        (\(appX), \(y)),
            'Applications': (\(appsX), \(y)),
        }
        """
    }
}
