/// Renders `.github/workflows/auto-release.yml` — push-to-main automation that
/// turns a version bump into a release.
///
/// On every push to `main` it reads the app version from the version source
/// (`relios version`) and, if no `v<version>` tag exists yet, creates and
/// pushes that tag. Pushing the tag triggers `release.yml` (which is gated on
/// `tags: ['v*']`), so the actual build/sign/notarize/publish/feed work isn't
/// duplicated here. If the version is unchanged (tag already exists), it's a
/// no-op — ordinary commits don't cut releases.
///
/// Only generated when `[update].enabled`, since the auto-update feed is what
/// makes continuous "push a version bump → users get it" meaningful.
public struct AutoReleaseWorkflowRenderer: Sendable {
    // Pinned in sync with the other renderers so one review covers all three.
    private static let checkoutSHA = "de0fac2e4500dabe0009e67214ff5f5447ce83dd" // v6.0.2

    public init() {}

    public func render(_ spec: ReleaseSpec) -> String {
        return """
        # Generated by `relios ci init`. Edit freely — re-running with --force overwrites.
        # Auto-release on version change: a push to main that lands a new version in
        # the version source is tagged `v<version>`, which triggers release.yml.
        # Unchanged version → no tag, no release. Enable/disable via [update] in relios.toml.
        name: Auto Release

        on:
          push:
            branches: [main]

        # Least privilege at the top; the tagging job escalates to write.
        permissions:
          contents: read

        concurrency:
          group: relios-auto-release-${{ github.ref }}
          cancel-in-progress: false

        jobs:
          tag-on-version-change:
            runs-on: macos-15
            permissions:
              contents: write
            steps:
              - uses: actions/checkout@\(Self.checkoutSHA) # v6.0.2
                with:
                  fetch-depth: 0

              - name: Install Relios
                run: brew install papa-channy/relios/relios

              - name: Tag new version
                run: |
                  VERSION=$(relios version)
                  TAG="v${VERSION}"
                  if git rev-parse "$TAG" >/dev/null 2>&1; then
                    echo "Tag $TAG already exists — version unchanged, skipping."
                    exit 0
                  fi
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git tag "$TAG"
                  git push origin "$TAG"
                  echo "Created and pushed $TAG → release.yml will build and publish."
        """
    }
}
