/// Renders `.github/workflows/ci.yml` — PR + push build/test gate.
///
/// Branches on `project.type` because the build/test commands differ:
///   - `.swiftpm`    — `swift build` + `swift test --parallel`
///   - `.xcodebuild` — runs the user's build command; no test step by
///     default because the test scheme is not encoded in `relios.toml`.
///     A commented TODO points the user at `xcodebuild test`.
public struct CIWorkflowRenderer: Sendable {
    // Pinned in sync with ReleaseWorkflowRenderer so one review covers both.
    private static let checkoutSHA   = "de0fac2e4500dabe0009e67214ff5f5447ce83dd" // v6.0.2
    private static let setupXcodeSHA = "ed7a3b1fda3918c0306d1b724322adc0b8cc0a90" // v1.7.0
    private static let cacheSHA      = "668228422ae6a00e4ad889ee87cd7109ec5666a7" // v5.0.4

    public init() {}

    /// `hasTests` controls whether the SwiftPM CI emits a `swift test` step.
    /// `swift test --parallel` exits 1 when no tests exist — emitting the
    /// step unconditionally turns an intentional "no tests yet" state into
    /// a red build. Pass `false` when the project has no `Tests/` directory.
    public func render(_ spec: ReleaseSpec, hasTests: Bool = true) -> String {
        switch spec.project.type {
        case .swiftpm:
            return renderSwiftPM(spec, hasTests: hasTests)
        case .xcodebuild:
            return renderXcodebuild(spec)
        }
    }

    // MARK: - SwiftPM

    private func renderSwiftPM(_ spec: ReleaseSpec, hasTests: Bool) -> String {
        let testStep = hasTests
            ? """


              - name: Test
                run: swift test --parallel
        """
            : """


              # No Tests/ directory detected at init time. Add one and
              # re-run `relios ci init --force` to enable the test step.
        """
        return """
        # Generated by `relios ci init`. Edit freely — re-running with --force overwrites.
        name: CI

        on:
          push:
            branches: [main]
          pull_request:
            branches: [main]

        jobs:
          build-test:
            runs-on: macos-15
            steps:
              - uses: actions/checkout@\(Self.checkoutSHA) # v6.0.2

              - uses: maxim-lobanov/setup-xcode@\(Self.setupXcodeSHA) # v1.7.0
                with:
                  xcode-version: latest-stable

              - name: Show toolchain
                run: swift --version

              - name: Cache SwiftPM
                uses: actions/cache@\(Self.cacheSHA) # v5.0.4
                with:
                  path: |
                    .build
                    ~/Library/Caches/org.swift.swiftpm
                  key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
                  restore-keys: |
                    ${{ runner.os }}-spm-

              - name: Build
                run: swift build -c release\(testStep)
        """
    }

    // MARK: - Xcode

    private func renderXcodebuild(_ spec: ReleaseSpec) -> String {
        let appName  = spec.app.name
        let buildCmd = spec.build.command

        return """
        # Generated by `relios ci init`. Edit freely — re-running with --force overwrites.
        #
        # TODO: enable tests. Replace the build step with:
        #   xcodebuild -scheme \(appName) -configuration Debug \\
        #     -destination 'platform=macOS' test
        # (the test scheme is not encoded in relios.toml, so we can't infer it.)
        name: CI

        on:
          push:
            branches: [main]
          pull_request:
            branches: [main]

        jobs:
          build:
            runs-on: macos-15
            steps:
              - uses: actions/checkout@\(Self.checkoutSHA) # v6.0.2

              - uses: maxim-lobanov/setup-xcode@\(Self.setupXcodeSHA) # v1.7.0
                with:
                  xcode-version: latest-stable

              - name: Build
                run: \(buildCmd)
        """
    }
}
