/// Renders a GitHub Actions `release.yml` tailored to a `ReleaseSpec`.
///
/// Phase 2 scope: ad-hoc signed `.app` → zipped → attached to GitHub Release.
/// Optional DMG output when `[dmg].enabled`. No Developer ID / notarization
/// yet — those arrive in Phase 2-4.
///
/// Branching:
///   - `bundle.mode` — passthrough (user's xcodebuild produces the .app) vs
///     assembly (Relios must be installed in CI to produce the .app).
///   - `[dmg]` presence — adds `pip install dmgbuild`, `relios dmg`, and
///     globs *.dmg from `[dmg].output_dir` into the release.
///
/// Both modes install Relios via Homebrew when DMG is enabled, since
/// `relios dmg` is what invokes dmgbuild.
public struct ReleaseWorkflowRenderer: Sendable {
    private static let checkoutSHA   = "de0fac2e4500dabe0009e67214ff5f5447ce83dd" // v6.0.2
    private static let setupXcodeSHA = "ed7a3b1fda3918c0306d1b724322adc0b8cc0a90" // v1.7.0
    private static let ghReleaseSHA  = "b4309332981a82ec1c5618f44dd2e27cc8bfbfda" // v3.0.0

    public init() {}

    public func render(_ spec: ReleaseSpec) -> String {
        let dmgEnabled    = spec.dmg?.enabled == true
        let devIDSigning  = spec.signing.mode == .developerID
        let notarize      = spec.notarize?.enabled == true
        let updateEnabled = spec.update?.enabled == true

        let header     = self.header(
            spec: spec,
            dmgEnabled: dmgEnabled,
            devIDSigning: devIDSigning,
            notarize: notarize,
            updateEnabled: updateEnabled
        )
        // Full history + tags so the update step can build release notes from
        // `git log`/`git describe` between the previous tag and this one.
        let fetchDepth = updateEnabled ? "\n          fetch-depth: 0" : ""
        let keychain   = devIDSigning ? keychainSetupBlock() + "\n\n" : ""
        let buildSteps = buildStepsBlock(spec: spec, dmgEnabled: dmgEnabled, updateEnabled: updateEnabled)
        let dmgSteps   = dmgEnabled ? dmgStepsBlock(spec: spec) : ""
        let notarizeSteps = notarize ? notarizeStepsBlock(spec: spec, dmgEnabled: dmgEnabled) : ""
        let updateSteps = updateEnabled ? updateStepsBlock() : ""
        let uploadStep = publishStep(spec: spec, dmgEnabled: dmgEnabled, updateEnabled: updateEnabled)
        let cleanup    = devIDSigning ? keychainCleanupBlock() : ""

        return """
        \(header)
        jobs:
          release:
            runs-on: macos-15
            permissions:
              contents: write
            steps:
              - uses: actions/checkout@\(Self.checkoutSHA) # v6.0.2
                with:
                  ref: ${{ github.event.inputs.tag || github.ref_name }}\(fetchDepth)
        \(keychain)\(buildSteps)\(dmgSteps)\(notarizeSteps)\(updateSteps)
        \(uploadStep)\(cleanup)
        """
    }

    // MARK: - header

    private func header(
        spec: ReleaseSpec,
        dmgEnabled: Bool,
        devIDSigning: Bool,
        notarize: Bool,
        updateEnabled: Bool
    ) -> String {
        let dmgNote = dmgEnabled
            ? "# DMG output enabled ([dmg].enabled = true) — `dmgbuild` is installed via pip.\n"
            : ""
        let signingNote = devIDSigning
            ? """
            # Developer ID signing enabled ([signing].mode = "developer-id"). Required repo secrets:
            #   APPLE_CERTIFICATE           — base64-encoded Developer ID Application .p12
            #   APPLE_CERTIFICATE_PASSWORD  — password used when exporting the .p12
            #   KEYCHAIN_PASSWORD           — any string; used to lock the temp keychain
            # The keychain is created fresh per run and deleted on exit.

            """
            : ""
        let notarizeNote = notarize
            ? """
            # Notarization enabled ([notarize].enabled = true). Required repo secrets:
            #   APPLE_ID                    — Apple Developer account email
            #   APPLE_APP_SPECIFIC_PASSWORD — appleid.apple.com → Security → App-Specific Passwords
            #   APPLE_TEAM_ID               — 10-char Team ID (must match [signing].team_id)
            # Apple's queue can take 2-15 minutes; the job waits inline.

            """
            : ""
        let updateNote = updateEnabled
            ? """
            # Auto-update feed enabled ([update].enabled = true). After publishing,
            # `relios update generate` writes update.json (version, download URL,
            # release notes) and it is uploaded as a Release asset. The shipped app
            # polls https://github.com/<owner>/<repo>/releases/latest/download/update.json.

            """
            : ""
        return """
        # Generated by `relios ci init`. Edit freely — re-running with --force overwrites.
        # Scope: build → sign → DMG → notarize → staple → publish → update-feed.
        # Optional blocks are conditioned on the corresponding relios.toml section.
        \(dmgNote)\(signingNote)\(notarizeNote)\(updateNote)name: Release

        on:
          push:
            tags: ['v*']
          workflow_dispatch:
            inputs:
              tag:
                description: 'Existing tag to (re-)release, e.g. v0.1.0'
                required: true

        # Least privilege at the top; the release job escalates to write.
        permissions:
          contents: read

        concurrency:
          group: relios-release-${{ github.ref }}
          cancel-in-progress: false
        """
    }

    // MARK: - build steps

    private func buildStepsBlock(spec: ReleaseSpec, dmgEnabled: Bool, updateEnabled: Bool) -> String {
        // Relios is needed to assemble (.app), to build a DMG, and to generate
        // the update manifest — install it whenever any of those apply.
        let needsRelios = dmgEnabled || updateEnabled || spec.bundle.mode == .assembly
        let installRelios = needsRelios
            ? """
              - name: Install Relios
                run: brew install papa-channy/relios/relios
        """
            : ""

        let installDMGBuild = dmgEnabled
            ? """
              - name: Install dmgbuild
                run: pip install --break-system-packages dmgbuild
        """
            : ""

        let setupXcode = spec.bundle.mode == .passthrough
            ? """
              - uses: maxim-lobanov/setup-xcode@\(Self.setupXcodeSHA) # v1.7.0
                with:
                  xcode-version: latest-stable
        """
            : ""

        let build: String
        switch spec.bundle.mode {
        case .passthrough:
            build = """
              - name: Build
                run: \(spec.build.displayCommand)
        """
        case .assembly:
            build = """
              - name: Build + assemble .app
                run: relios release --skip-backup --no-open
        """
        }

        let verify = """
              - name: Verify app bundle
                run: test -d "\(spec.bundle.outputPath)"
        """

        let packageZip = """
              - name: Package .app
                env:
                  TAG: ${{ github.event.inputs.tag || github.ref_name }}
                run: |
                  ZIP="\(spec.app.name)-${TAG}.zip"
                  ditto -c -k --sequesterRsrc --keepParent "\(spec.bundle.outputPath)" "$ZIP"
                  echo "ZIP=$ZIP" >> "$GITHUB_ENV"
        """

        return [setupXcode, installRelios, installDMGBuild, build, verify, packageZip]
            .filter { !$0.isEmpty }
            .joined(separator: "\n\n")
    }

    // MARK: - DMG steps

    private func dmgStepsBlock(spec: ReleaseSpec) -> String {
        guard let dmg = spec.dmg else { return "" }
        // Resolve the single DMG path so downstream steps (notarize,
        // publish) can pass it explicitly instead of shell-globbing.
        return """


              - name: Create DMG
                run: relios dmg

              - name: Record DMG path
                run: |
                  DMG_FILE=$(ls \(dmg.outputDir)/*.dmg | head -1)
                  echo "DMG_FILE=$DMG_FILE" >> "$GITHUB_ENV"
        """
    }

    // MARK: - publish

    private func publishStep(spec: ReleaseSpec, dmgEnabled: Bool, updateEnabled: Bool) -> String {
        // Assemble the artifact list in pipeline order: zip, then DMG, then the
        // update feed (uploaded with a stable name so the app's
        // releases/latest/download/<feed> URL resolves).
        var fileLines = ["${{ env.ZIP }}"]
        if dmgEnabled { fileLines.append("${{ env.DMG_FILE }}") }
        if updateEnabled, let update = spec.update {
            let feed = update.outputDir + "/" + update.feedFileName
            fileLines.append(feed)
            fileLines.append(feed + ".sig")   // present when RELIOS_UPDATE_SIGNING_KEY is set
        }

        let filesField: String
        if fileLines.count == 1 {
            filesField = "          files: \(fileLines[0])"
        } else {
            let body = fileLines.map { "            " + $0 }.joined(separator: "\n")
            filesField = "          files: |\n" + body
        }

        return """
              - name: Publish GitHub Release
                uses: softprops/action-gh-release@\(Self.ghReleaseSHA) # v3.0.0
                with:
                  tag_name: ${{ github.event.inputs.tag || github.ref_name }}
                  generate_release_notes: true
        \(filesField)
        """
    }

    // MARK: - update feed

    /// Generates `update.json` from the just-published artifacts. Runs after
    /// notarize and before publish so the feed is uploaded alongside the
    /// release. The artifact filename is resolved from `$DMG_FILE` (if a DMG
    /// was built) or `$ZIP`, and release notes come from `git log` between the
    /// previous tag and this one.
    private func updateStepsBlock() -> String {
        return """


              - name: Verify tag matches AppVersion
                env:
                  TAG: ${{ github.event.inputs.tag || github.ref_name }}
                run: |
                  EXPECTED="v$(relios version)"
                  if [ "${TAG}" != "$EXPECTED" ]; then
                    echo "::error::tag ${TAG} does not match AppVersion ${EXPECTED}"
                    exit 1
                  fi

              - name: Generate update manifest
                env:
                  TAG: ${{ github.event.inputs.tag || github.ref_name }}
                  RELIOS_UPDATE_SIGNING_KEY: ${{ secrets.RELIOS_UPDATE_SIGNING_KEY }}
                run: |
                  ASSET=$(basename "${DMG_FILE:-$ZIP}")
                  URL="https://github.com/${{ github.repository }}/releases/download/${TAG}/${ASSET}"
                  PREV=$(git describe --tags --abbrev=0 "${TAG}^" 2>/dev/null || true)
                  if [ -n "$PREV" ]; then
                    git log --pretty='- %s' "${PREV}..${TAG}" > "$RUNNER_TEMP/notes.txt"
                  else
                    git log --pretty='- %s' > "$RUNNER_TEMP/notes.txt"
                  fi
                  relios update generate \\
                    --tag "${TAG}" \\
                    --repo "${{ github.repository }}" \\
                    --download-url "${URL}" \\
                    --artifact "${DMG_FILE:-$ZIP}" \\
                    --commit "${{ github.sha }}" \\
                    --notes-file "$RUNNER_TEMP/notes.txt" \\
                    --notes-url "https://github.com/${{ github.repository }}/releases/tag/${TAG}"
        """
    }

    // MARK: - keychain (Developer ID signing)

    /// Imports the base64-encoded Developer ID `.p12` secret into a
    /// throwaway keychain named `relios-signing.keychain-db`. Prepends it
    /// to the default search list so `codesign` picks up the identity
    /// without prompting, and runs `set-key-partition-list` so the
    /// non-interactive session can actually sign.
    ///
    /// A separate `if: always()` cleanup step deletes the keychain at the
    /// end of the job; we don't use a shell `trap` because each GHA step
    /// is a fresh shell.
    private func keychainSetupBlock() -> String {
        return """


              - name: Import Developer ID certificate
                env:
                  APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
                  APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
                  KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
                run: |
                  set -euo pipefail
                  KEYCHAIN=$RUNNER_TEMP/relios-signing.keychain-db
                  CERT_PATH=$RUNNER_TEMP/relios-cert.p12
                  echo "$APPLE_CERTIFICATE" | base64 --decode > "$CERT_PATH"
                  security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN"
                  security set-keychain-settings -lut 21600 "$KEYCHAIN"
                  security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN"
                  security import "$CERT_PATH" -k "$KEYCHAIN" \\
                    -P "$APPLE_CERTIFICATE_PASSWORD" \\
                    -T /usr/bin/codesign
                  security set-key-partition-list \\
                    -S apple-tool:,apple:,codesign: \\
                    -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN"
                  security list-keychains -d user -s "$KEYCHAIN" $(security list-keychains -d user | tr -d '"')
                  rm -f "$CERT_PATH"
        """
    }

    // MARK: - notarize

    /// Injects a single `relios notarize` step. It handles DMG (staples
    /// directly) and zip (unzip → staple `.app` → re-zip) uniformly, so
    /// the workflow doesn't need to know which target resolved.
    ///
    /// For the zip path we also re-export `ZIP` after notarize so the
    /// publish step's `${{ env.ZIP }}` still resolves (`relios notarize`
    /// rewrites the zip in place with the stapled `.app` inside).
    private func notarizeStepsBlock(spec: ReleaseSpec, dmgEnabled: Bool) -> String {
        // Pass the artifact explicitly so the resolver doesn't guess the
        // filename from AppVersion.swift — the actual filename is built
        // from the git tag, which can diverge from the source version.
        let artifact = dmgEnabled ? "$DMG_FILE" : "$ZIP"
        return """


              - name: Notarize + staple
                env:
                  APPLE_ID: ${{ secrets.APPLE_ID }}
                  APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
                  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
                run: relios notarize "\(artifact)"
        """
    }

    private func keychainCleanupBlock() -> String {
        return """


              - name: Delete signing keychain
                if: always()
                run: |
                  KEYCHAIN=$RUNNER_TEMP/relios-signing.keychain-db
                  if [ -f "$KEYCHAIN" ]; then
                    security delete-keychain "$KEYCHAIN" || true
                  fi
        """
    }
}
